/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Protocol"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_PDU_H_
#define	_PDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Request.h"
#include "Response.h"
#include "Verification.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDU_PR {
	PDU_PR_NOTHING,	/* No components present */
	PDU_PR_request,
	PDU_PR_response,
	PDU_PR_verification
} PDU_PR;

/* PDU */
typedef struct PDU {
	PDU_PR present;
	union PDU_u {
		Request_t	 request;
		Response_t	 response;
		Verification_t	 verification;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDU;

#ifdef __cplusplus
}
#endif

#endif	/* _PDU_H_ */
