/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Protocol"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_Response_H_
#define	_Response_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <PrintableString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Response */
typedef struct Response {
	long	 value;
	PrintableString_t	 randStr;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Response_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Response;

#ifdef __cplusplus
}
#endif

#endif	/* _Response_H_ */
