/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Protocol"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons`
 */

#ifndef	_Verification_H_
#define	_Verification_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum result {
	result_ok	= 0,
	result_fail	= 1
} e_result;

/* Verification */
typedef struct Verification {
	long	 result;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Verification_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_result_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Verification;

#ifdef __cplusplus
}
#endif

#endif	/* _Verification_H_ */
