package callback;


/**
* callback/NoSuchStock.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callback.idl
* Sonntag, 25. Mai 2014 13:25 Uhr MESZ
*/

public final class NoSuchStock extends org.omg.CORBA.UserException
{

  public NoSuchStock ()
  {
    super(NoSuchStockHelper.id());
  } // ctor


  public NoSuchStock (String $reason)
  {
    super(NoSuchStockHelper.id() + "  " + $reason);
  } // ctor

} // class NoSuchStock
