package callback.Client_Handler;


/**
* callback/Client_Handler/ServerpushOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callback.idl
* Sonntag, 25. Mai 2014 13:25 Uhr MESZ
*/

public interface ServerpushOperations 
{
  void push (callback.Client_Handler.Stock data);
} // interface ServerpushOperations
