package callback.Client_Handler;


/**
* callback/Client_Handler/Serverpush.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callback.idl
* Sonntag, 25. Mai 2014 13:25 Uhr MESZ
*/

public interface Serverpush extends ServerpushOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Serverpush
