package callback.Client_Handler;


/**
* callback/Client_Handler/ServerpushPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callback.idl
* Sonntag, 25. Mai 2014 13:25 Uhr MESZ
*/

public abstract class ServerpushPOA extends org.omg.PortableServer.Servant
 implements callback.Client_Handler.ServerpushOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("push", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // callback/Client_Handler/Serverpush/push
       {
         callback.Client_Handler.Stock data = callback.Client_Handler.StockHelper.read (in);
         this.push (data);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:callback/Client_Handler/Serverpush:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Serverpush _this() 
  {
    return ServerpushHelper.narrow(
    super._this_object());
  }

  public Serverpush _this(org.omg.CORBA.ORB orb) 
  {
    return ServerpushHelper.narrow(
    super._this_object(orb));
  }


} // class ServerpushPOA
