package callback.Client_Handler;

/**
* callback/Client_Handler/ServerpushHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callback.idl
* Sonntag, 25. Mai 2014 13:25 Uhr MESZ
*/

public final class ServerpushHolder implements org.omg.CORBA.portable.Streamable
{
  public callback.Client_Handler.Serverpush value = null;

  public ServerpushHolder ()
  {
  }

  public ServerpushHolder (callback.Client_Handler.Serverpush initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = callback.Client_Handler.ServerpushHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    callback.Client_Handler.ServerpushHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return callback.Client_Handler.ServerpushHelper.type ();
  }

}
