package callback.Client_Handler;


/**
* callback/Client_Handler/Stock.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callback.idl
* Sonntag, 25. Mai 2014 13:25 Uhr MESZ
*/

public final class Stock implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String isn = null;
  public double price = (double)0;

  public Stock ()
  {
  } // ctor

  public Stock (String _name, String _isn, double _price)
  {
    name = _name;
    isn = _isn;
    price = _price;
  } // ctor

} // class Stock
