package Specfication;

/**
* Specfication/NoSuchStockHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Specfication.idl
* Donnerstag, 22. Mai 2014 11:46 Uhr MESZ
*/

public final class NoSuchStockHolder implements org.omg.CORBA.portable.Streamable
{
  public Specfication.NoSuchStock value = null;

  public NoSuchStockHolder ()
  {
  }

  public NoSuchStockHolder (Specfication.NoSuchStock initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Specfication.NoSuchStockHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Specfication.NoSuchStockHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Specfication.NoSuchStockHelper.type ();
  }

}
