package Specfication;


/**
* Specfication/NoSuchStock.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Specfication.idl
* Donnerstag, 22. Mai 2014 11:46 Uhr MESZ
*/

public final class NoSuchStock extends org.omg.CORBA.UserException
{

  public NoSuchStock ()
  {
    super(NoSuchStockHelper.id());
  } // ctor


  public NoSuchStock (String $reason)
  {
    super(NoSuchStockHelper.id() + "  " + $reason);
  } // ctor

} // class NoSuchStock
