package Specfication;


/**
* Specfication/quoter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Specfication.idl
* Donnerstag, 22. Mai 2014 11:46 Uhr MESZ
*/

public interface Quoter extends QuoterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface quoter
