package Specfication;


/**
* Specfication/quoterPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Specfication.idl
* Donnerstag, 22. Mai 2014 11:46 Uhr MESZ
*/

public abstract class quoterPOA extends org.omg.PortableServer.Servant
 implements Specfication.quoterOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getStockByIsn", new java.lang.Integer (0));
    _methods.put ("getStockByName", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Specfication/quoter/getStockByIsn
       {
         try {
           String isn = in.read_string ();
           double $result = (double)0;
           $result = this.getStockByIsn (isn);
           out = $rh.createReply();
           out.write_double ($result);
         } catch (Specfication.NoSuchStock $ex) {
           out = $rh.createExceptionReply ();
           Specfication.NoSuchStockHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // Specfication/quoter/getStockByName
       {
         try {
           String name = in.read_string ();
           double $result = (double)0;
           $result = this.getStockByName (name);
           out = $rh.createReply();
           out.write_double ($result);
         } catch (Specfication.NoSuchStock $ex) {
           out = $rh.createExceptionReply ();
           Specfication.NoSuchStockHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Specfication/quoter:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public quoter _this() 
  {
    return quoterHelper.narrow(
    super._this_object());
  }

  public quoter _this(org.omg.CORBA.ORB orb) 
  {
    return quoterHelper.narrow(
    super._this_object(orb));
  }


} // class quoterPOA
