package Specfication;

/**
* Specfication/quoterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Specfication.idl
* Donnerstag, 22. Mai 2014 11:46 Uhr MESZ
*/

public final class quoterHolder implements org.omg.CORBA.portable.Streamable
{
  public Specfication.quoter value = null;

  public quoterHolder ()
  {
  }

  public quoterHolder (Specfication.quoter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Specfication.quoterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Specfication.quoterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Specfication.quoterHelper.type ();
  }

}
