package callback.Server_Handler;


/**
* callback/Server_Handler/_Server_RegisterStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callback.idl
* Sonntag, 25. Mai 2014 13:25 Uhr MESZ
*/

public class _Server_RegisterStub extends org.omg.CORBA.portable.ObjectImpl implements callback.Server_Handler.Server_Register
{

  public void register_stock (callback.Client_Handler.Serverpush client, String stockname) throws callback.NoSuchStock
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("register_stock", true);
                callback.Client_Handler.ServerpushHelper.write ($out, client);
                $out.write_string (stockname);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:callback/NoSuchStock:1.0"))
                    throw callback.NoSuchStockHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                register_stock (client, stockname        );
            } finally {
                _releaseReply ($in);
            }
  } // register_stock

  public void unregister_stock (callback.Client_Handler.Serverpush client, String stockname) throws callback.NoSuchStock
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("unregister_stock", true);
                callback.Client_Handler.ServerpushHelper.write ($out, client);
                $out.write_string (stockname);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:callback/NoSuchStock:1.0"))
                    throw callback.NoSuchStockHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                unregister_stock (client, stockname        );
            } finally {
                _releaseReply ($in);
            }
  } // unregister_stock

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:callback/Server_Handler/Server_Register:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _Server_RegisterStub
