package callback.Server_Handler;


/**
* callback/Server_Handler/Server_RegisterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callback.idl
* Sonntag, 25. Mai 2014 13:25 Uhr MESZ
*/

public interface Server_RegisterOperations 
{
  void register_stock (callback.Client_Handler.Serverpush client, String stockname) throws callback.NoSuchStock;
  void unregister_stock (callback.Client_Handler.Serverpush client, String stockname) throws callback.NoSuchStock;
} // interface Server_RegisterOperations
