package callback.Server_Handler;


/**
* callback/Server_Handler/Server_RegisterHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from callback.idl
* Sonntag, 25. Mai 2014 13:25 Uhr MESZ
*/

abstract public class Server_RegisterHelper
{
  private static String  _id = "IDL:callback/Server_Handler/Server_Register:1.0";

  public static void insert (org.omg.CORBA.Any a, callback.Server_Handler.Server_Register that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static callback.Server_Handler.Server_Register extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (callback.Server_Handler.Server_RegisterHelper.id (), "Server_Register");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static callback.Server_Handler.Server_Register read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Server_RegisterStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, callback.Server_Handler.Server_Register value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static callback.Server_Handler.Server_Register narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof callback.Server_Handler.Server_Register)
      return (callback.Server_Handler.Server_Register)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      callback.Server_Handler._Server_RegisterStub stub = new callback.Server_Handler._Server_RegisterStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static callback.Server_Handler.Server_Register unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof callback.Server_Handler.Server_Register)
      return (callback.Server_Handler.Server_Register)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      callback.Server_Handler._Server_RegisterStub stub = new callback.Server_Handler._Server_RegisterStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
